#!/bin/bash
# start-codex.sh — {{ROLE}} standby/session launcher (Codex CLI).
# Generated by agent-factory / butler-kit. Manual edits may be overwritten.

export PATH=$HOME/.bun/bin:$PATH
cd {{WORKDIR}}

CODEX_MODEL="${CODEX_MODEL:-${KIT_CODEX_MODEL:-gpt-5.3-codex}}"
COMMON_ARGS=(--model "$CODEX_MODEL" --dangerously-bypass-approvals-and-sandbox -C "{{WORKDIR}}" --no-alt-screen)

if codex "${COMMON_ARGS[@]}" resume --last 2>/dev/null; then
  :
else
  exec codex "${COMMON_ARGS[@]}"
fi
